/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ZERO
 */
public final class dlgCuenta extends javax.swing.JDialog {

    boolean reg;
    int pmod;
    private Connection cnn = null;
    Empleado empleado = new Empleado();
    Sucursal sucursal = new Sucursal();
    Cliente cliente = new Cliente();
    Moneda moneda = new Moneda();
    String fecha;

    public dlgCuenta() throws SQLException {
        super(FrmPrincipal.getInstancia(), false);
        cnn = Conexion.getInstancia().miConexion();
        initComponents();
        setLocationRelativeTo(null);
        generarCodigoCuenta();
        controles(true);
        textos(false);
        empleado.llenarComboEmpleado(cboEmpleado);
        sucursal.llenarComboSucursal(cboSucursal);
        cliente.llenarComboCliente(cboCliente);
        moneda.llenarComboMoneda(cboMoneda);
        fecha = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        txtFecha.setText(fecha);
        lblMoneda.setVisible(false);
        lblEmpleado.setVisible(false);
        lblSucursal.setVisible(false);
        lblCliente.setVisible(false);
        txtCliente.setVisible(false);
        txtSucursal.setVisible(false);
        txtEmpleado.setVisible(false);
        txtMoneda.setVisible(false);
    }

    void generarCodigoCuenta() throws SQLException {
        String serie = CuentaDAO.getInstancia().codigoCuenta();
        if (serie == null) {
            txtCodigo.setText("00001");
        } else {
            int increment = Integer.parseInt(serie);
            increment = increment + 1;
            if (txtCodigo.getText().compareTo("00009") == 0) {
                txtCodigo.setText("000" + increment);
            } else {
                txtCodigo.setText("00" + increment);
            }
        }
    }

    void limpiarTextos() {
//        txtFechaIngreso.setText("");
//        txtFechaBaja.setText("");
        cboEstado.setSelectedIndex(0);
    }

    void controles(boolean sw) {
        btnNuevo.setEnabled(sw);
        btnAperturar.setEnabled(!sw);
        btcancelar.setEnabled(!sw);
        btnBuscar.setEnabled(sw);
        btnEliminar.setEnabled(sw);
        btnModificar.setEnabled(sw);
        btnlimpiar.setEnabled(!sw);
    }
    
    void textos(boolean sw) {
        txtClave.setEditable(sw);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboEmpleado = new javax.swing.JComboBox<>();
        lblEmpleado1 = new javax.swing.JLabel();
        cboSucursal = new javax.swing.JComboBox<>();
        lblSucursal1 = new javax.swing.JLabel();
        lblCliente1 = new javax.swing.JLabel();
        cboCliente = new javax.swing.JComboBox<>();
        btnAperturar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblMoneda1 = new javax.swing.JLabel();
        cboMoneda = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumMovimientos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblSucursal = new javax.swing.JLabel();
        txtSucursal = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblEmpleado = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JTextField();
        lblMoneda = new javax.swing.JLabel();
        txtMoneda = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCodigo.setEditable(false);

        jLabel2.setText("Codigo");

        lblEmpleado1.setText("Empleado");

        lblSucursal1.setText("Sucursal");

        lblCliente1.setText("Cliente");

        btnAperturar.setText("Registrar");
        btnAperturar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAperturar.setContentAreaFilled(false);
        btnAperturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAperturarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimpiar.setContentAreaFilled(false);
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btcancelar.setText("Cancelar");
        btcancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btcancelar.setContentAreaFilled(false);
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.setContentAreaFilled(false);
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModificarMousePressed(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblMoneda1.setText("Moneda");

        jLabel7.setText("Saldo");

        txtSaldo.setEditable(false);

        jLabel8.setText("<html>Numero de Movimientos</html>");

        txtNumMovimientos.setEditable(false);

        jLabel9.setText("Estado");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ...", "ACTIVO", "ANULADO", "CANCELADO" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Clave");

        jLabel11.setText("Fecha");

        txtFecha.setEditable(false);

        lblSucursal.setText("Sucursal");

        txtSucursal.setEditable(false);

        lblCliente.setText("Cliente");

        txtCliente.setEditable(false);

        lblEmpleado.setText("Empleado");

        txtEmpleado.setEditable(false);

        lblMoneda.setText("Moneda");

        txtMoneda.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMoneda1)
                        .addGap(5, 5, 5)
                        .addComponent(cboMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(936, 936, 936)
                            .addComponent(jLabel11)
                            .addGap(5, 5, 5)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(22, 22, 22)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblMoneda)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSucursal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(txtNumMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(5, 5, 5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cboEstado, 0, 249, Short.MAX_VALUE)
                                .addComponent(txtCliente))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmpleado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(jLabel2)
                            .addGap(5, 5, 5)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(lblSucursal1)
                            .addGap(5, 5, 5)
                            .addComponent(cboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblCliente1)
                            .addGap(18, 18, 18)
                            .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(lblEmpleado1)
                            .addGap(5, 5, 5)
                            .addComponent(cboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(433, 433, 433)
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnAperturar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel11))
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblSucursal1)
                            .addComponent(lblCliente1)
                            .addComponent(lblEmpleado1))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel9))
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblMoneda1))
                    .addComponent(cboMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSucursal)
                            .addComponent(lblMoneda)
                            .addComponent(txtMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpleado)
                            .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCliente)
                            .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10))
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAperturar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAperturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAperturarActionPerformed
        // TODO add your handling code here:
        String codigoCuenta, codigoMoneda, codigoSucursal, codigoEmpleado, codigoCliente, clave, estado;
        float saldo;
        int numMovimiento;
        if (txtSaldo.getText().compareTo("") != 0) {
            try {

                codigoCuenta = txtCodigo.getText();
                codigoMoneda = cboMoneda.getItemAt(cboMoneda.getSelectedIndex()).getMonecodigo();
                codigoSucursal = cboSucursal.getItemAt(cboSucursal.getSelectedIndex()).getSucucodigo();
                codigoEmpleado = cboEmpleado.getItemAt(cboEmpleado.getSelectedIndex()).getEmplcodigo();
                codigoCliente = cboCliente.getItemAt(cboCliente.getSelectedIndex()).getCliecodigo();
                saldo = Float.parseFloat(txtSaldo.getText());
                estado = (String) cboEstado.getSelectedItem();
                numMovimiento = Integer.parseInt(txtNumMovimientos.getText());
                clave = txtClave.getText();
                if (reg) {
                    try {
                        CuentaDAO.getInstancia().insertar(codigoCuenta, codigoMoneda, codigoSucursal,
                                codigoEmpleado, codigoCliente, saldo, fecha, estado, numMovimiento, clave);
                        JOptionPane.showMessageDialog(null, "Dato registrado");
                        generarCodigoCuenta();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }

                } else {
                    try {
                        CuentaDAO.getInstancia().actualizar(codigoCuenta, codigoMoneda, codigoSucursal,
                                codigoEmpleado, codigoCliente, saldo, fecha, estado, numMovimiento, clave);
                        JOptionPane.showMessageDialog(null, "Dato modificado");
                        btnAperturar.setText("Modificar");
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }

                }
                generarCodigoCuenta();
                limpiarTextos();
                controles(true);
                textos(false);

            } catch (SQLException ex) {
                Logger.getLogger(dlgEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "faltan llenar datos");
        }
    }//GEN-LAST:event_btnAperturarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        reg = true;
        controles(false);
        textos(true);
        limpiarTextos();
        txtNumMovimientos.setEditable(false);
        txtNumMovimientos.setText("0");
        txtSaldo.requestFocus();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        limpiarTextos();
        txtSaldo.requestFocus();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        // TODO add your handling code here:
        limpiarTextos();
        textos(true);
        controles(true);
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btnModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMousePressed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String codigo;
        limpiarTextos();
        codigo = JOptionPane.showInputDialog("Ingrese el codigo de la cuenta a modificar : ");
        Cuenta x;
        try {
            x = CuentaDAO.getInstancia().buscarCuenta(codigo);
            if (x != null) {
                lblMoneda.setVisible(true);
                lblEmpleado.setVisible(true);
                lblSucursal.setVisible(true);
                lblCliente.setVisible(true);
                txtCliente.setVisible(true);
                txtSucursal.setVisible(true);
                txtEmpleado.setVisible(true);
                txtMoneda.setVisible(true);
                lblMoneda1.setVisible(false);
                lblEmpleado1.setVisible(false);
                lblSucursal1.setVisible(false);
                lblCliente1.setVisible(false);
                cboCliente.setVisible(false);
                cboEmpleado.setVisible(false);
                cboSucursal.setVisible(false);
                cboMoneda.setVisible(false);
                txtCodigo.setText(x.getCuencodigo());
                txtSaldo.setText(String.valueOf(x.getCuensaldo()));
                txtNumMovimientos.setText(String.valueOf(x.getCuencontmov()));
                txtClave.setText(x.getCuenclave());
                txtSucursal.setText(x.getSucucodigo());
                txtCliente.setText(x.getCliecodigo());
                txtEmpleado.setText(x.getEmplcreacuenta());
                txtMoneda.setText(x.getMonecodigo());
                x.setCuenestado((String) cboEstado.getSelectedItem());
                reg = false;
                controles(false);
                textos(true);
            } else {
                JOptionPane.showMessageDialog(null, "El codigo Asignado no existe");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
//        String codigo;
//        int p;
//        limpiarTextos();
//        codigo = JOptionPane.showInputDialog("El codigo del cliente a eliminar : ");
//        Asignado x;
//        try {
//            x = AsignadoDAO.getInstancia().buscarAsignado(codigo);
//            if (x != null) {
//                txtCodigo.setText(x.getEmplcodigo());
//                txtFechaIngreso.setText(x.getAsigfechaalta());
//                txtFechaBaja.setText(x.getAsigfechabaja());
//                int resp = JOptionPane.showConfirmDialog(this, "Deseas Eliminarlo ", "Eliminar Dato", JOptionPane.YES_NO_OPTION);
//                if (resp == JOptionPane.YES_OPTION) {
//                    EmpleadoDAO.getInstancia().eliminar(codigo);
//                    JOptionPane.showMessageDialog(this, "Registro eliminado");
//                }
//                generarCodigoAsignado();
//                limpiarTextos();
//            } else {
//                JOptionPane.showMessageDialog(null, "El codigo del cliente no existe");
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, ex.getMessage());
//        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String cuenta;
        limpiarTextos();
        cuenta = JOptionPane.showInputDialog("Ingrese el codigo de la cuenta a buscar : ");
        Cuenta x;
        try {
            x = CuentaDAO.getInstancia().buscarCuenta(cuenta);
            if (x != null) {
                lblMoneda.setVisible(true);
                lblEmpleado.setVisible(true);
                lblSucursal.setVisible(true);
                lblCliente.setVisible(true);
                txtCliente.setVisible(true);
                txtSucursal.setVisible(true);
                txtEmpleado.setVisible(true);
                txtMoneda.setVisible(true);
                lblMoneda1.setVisible(false);
                lblEmpleado1.setVisible(false);
                lblSucursal1.setVisible(false);
                lblCliente1.setVisible(false);
                cboCliente.setVisible(false);
                cboEmpleado.setVisible(false);
                cboSucursal.setVisible(false);
                cboMoneda.setVisible(false);
                
                txtCodigo.setText(x.getCuencodigo());
                x.setCuenestado((String) cboEstado.getSelectedItem());
                txtSaldo.setText(String.valueOf(x.getCuensaldo()));
                txtNumMovimientos.setText(String.valueOf(x.getCuencontmov()));
                txtClave.setText(x.getCuenclave());
                txtSucursal.setText(x.getSucucodigo());
                txtCliente.setText(x.getCliecodigo());
                txtEmpleado.setText(x.getEmplcreacuenta());
                txtMoneda.setText(x.getMonecodigo());

            } else {
                JOptionPane.showMessageDialog(null, "El codigo no existe");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btnAperturar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JComboBox<Cliente> cboCliente;
    private javax.swing.JComboBox<Empleado> cboEmpleado;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<Moneda> cboMoneda;
    private javax.swing.JComboBox<Sucursal> cboSucursal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblEmpleado1;
    private javax.swing.JLabel lblMoneda;
    private javax.swing.JLabel lblMoneda1;
    private javax.swing.JLabel lblSucursal;
    private javax.swing.JLabel lblSucursal1;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMoneda;
    private javax.swing.JTextField txtNumMovimientos;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSucursal;
    // End of variables declaration//GEN-END:variables
}
